### ISSUE TITLE
Question: Multiple limits in one testcase

### ISSUE THREAD

**Issue by GWiking** [slightlynybbled/mats#7]
What is the best way to handle multiple limits in one testcase. For example a stimulus for the DUT that outputs dc level and rms level that needs to be evaluated and logged?

**Comment by slightlynybbled** [comment]
Greetings -

I'm not sure what the problem domain is, but I can make a recommendation.  I would generally separate this into two test cases:

    class DcTest(Test):
        def __init__(self, instrument):
            super().__init__(moniker='dc level', max_value=24.0)
            self._instrument = instrument

        def setup(self, is_passing):
            ... # perform any setup or wait times

        def execute(self, is_passing):
            return self._instrument.read_dc()

    class RmsTest(Test):
        def __init__(self, instrument):
            super().__init__(moniker='rms level', max_value=30.0)
            self._instrument = instrument

        def setup(self, is_passing):
            ... # perform any setup or wait times

        def execute(self, is_passing):
            return self._instrument.read_rms()

Alternatively, you might want to make this a singular test in which you "manually" fail if things aren't in line.

    class VoltageTest(Test):
        def __init__(self, instrument):
            super().__init__(moniker='voltage level')  # can't pass a min_value or 
                                                       # max_value since this contains multiple values
            self._instrument = instrument

        def setup(self, is_passing):
            ... # perform any setup or wait times

        def execute(self, is_passing):
            v_dc = self._instrument.read_dc()
            v_rms = self._instrument.read_rms()

            if v_dc < 24.0 or v_rms < 30.0:
                self.fail()  # manually trigger a fail event

            return f'{v_dc} {v_rms}'  #  not sure how you would want to record this; have to be 
                                      # careful b/c two equivalent values will need to be returned 
                                      # if you want to record them

Good luck,

j

**Comment by GWiking** [comment]
Thank you for your fast response. Very good examples, in my case the second one will sometimes be preferable because there is some analytics that will be done for the sampled data from a DAQ.
